### ISSUE TITLE
JSONのキー

### ISSUE THREAD

**Issue by n04ln** [NoahOrberg/gilbert#1]
```
{
  "description" : "説明",
  "public" : false,
  "files" : {
    "hoge.txt" : {
      "content" : "ファイルの中身"
    }
  }
}
```
PayloadのJSONスキーマは↑である

Gistに上げるときにファイル名を指定するなら、StructをJSONにパースする性質上、タグを書き換えねばならない （ `hoge.txt` がそれに当たるがそれはキーであるため）
しかし、タグの書き換えができないので、stringでpayloadを組み立てるべきかとも思ったが `"` エスケープとかせねばならないので少し嫌なきもちになる

**Comment by upamune** [comment]
Filesがmapを持てば良さそう https://play.golang.org/p/L5JjZ0X1Kd

**Comment by n04ln** [comment]
なるほど、確かにできました！
ありがとうございます 🙇
